### ISSUE TITLE
what variant do we use in few-shot learning on ScanObjectNN?

### ISSUE THREAD

**Issue by TangYuan96** [MohamedAfham/CrossPoint#15]
Hi, thank you for sharing such excellent results

I would like to ask what variant do we use in few-shot learning on ScanObjectNN?

OBJ ONLY
OBJ BG
PB T25
PB T25 R
PB T50 R
PB T50 RS

Looking forward for your response, thank you

**Comment by SFMDI** [comment]
I think they used OBJ_BG/OBJ_ONLY. I downloaded and checked the ScanObjectNN dataset h5_files.zip and found that the h5 file they used was the same as training_objectdataset.h5 of h5_files.zip.

According to ScanObjectNN's naming convention, *objectdataset.h5 file is classified as OBJ_BG / OBJ_ONLY.
See https://github.com/hkust-vgd/scanobjectnn

**Comment by MohamedAfham** [comment]
Hi @TangYuan96,

As @SFMDI mentioned we used the OBJ_BG / OBJ_ONLY version of the dataset.
