### ISSUE TITLE
the definition of loss function 

### ISSUE THREAD

**Issue by hyxxx-alt** [MohamedAfham/CrossPoint#2]
Thank you for your excellent work. Which code can I find the definition of loss function (including imid and cmid) mentioned in the paper?

**Comment by MohamedAfham** [comment]
Thanks!

You can find the imid https://github.com/MohamedAfham/CrossPoint/blob/5a25088fd1186e3c72beda934a8833ea465ce487/train_crosspoint.py#L106 and cmid definition https://github.com/MohamedAfham/CrossPoint/blob/5a25088fd1186e3c72beda934a8833ea465ce487/train_crosspoint.py#L108
As mentioned in the paper, we have used NTXent Loss function as used in SimCLR paper. Refer to
https://github.com/MohamedAfham/CrossPoint/blob/5a25088fd1186e3c72beda934a8833ea465ce487/train_crosspoint.py#L76 for the usage.

**Comment by hyxxx-alt** [comment]
Thanks for your answer ! 

But it seems that the loss in your paper is a little different from the NT-Xent loss, it hasn't compute the similarity of different examples. I wonder why it can be referred directly for the usage.

**Comment by MohamedAfham** [comment]
Thanks for pointing that out !

Essentially our approach leverages the NT-Xent loss as explained in the paper. However as you said, there's small confusion in the notations of the equations. We are in the process of updating the paper for camera ready submission. We'll make the notations clear enough. Feel free to let me know if you couldn't reproduce the results.

**Comment by auniquesun** [comment]
@MohamedAfham nice work!

I have a similar question as above mentioned, in Equation (1) in the paper, both $z_i^{t1}$ and $z_i^{t2}$ come from a same input point cloud $P_i$, which implies that $z_k^{t1}$ and $z_k^{t2}$ are also generated by the same point cloud $P_k$. 

But the paper describes "The goal is to maxmize the similarity of $z_i^{t1}$ with $z_i^{t2}$ while **minimizing** the similarity with 
with all other projected vector ...". It is confused and also applies to Equation (3).

By the way, the mini-batch size is N, why does the variable k in Equation (1) end with 2N-1 rather than N?

**Comment by MohamedAfham** [comment]
Thanks for mentioning it. As I said in the previous comment, I admit that there is a confusion in the notations of the equations provided. However, the approach as clearly mentioned in the paper leverages NT-Xent loss for both IMID and CMID losses. Hence, I believe there won't be any issue in reproducing the reported results.

I have rephrased the equations below for clarity and it'll be then updated in the camera-ready version of the paper.

### IMID Loss

<img src = "https://latex.codecogs.com/svg.image?\mathcal{L}_{imid}&space;=&space;\frac{1}{2N}&space;\sum_{i=1}^{N}[l(i,{t_1},{t_2})&space;&plus;&space;l(i,{t_2},{t_1})]&space;"/>

where,

<img src = "https://latex.codecogs.com/svg.image?l(i,{t_1},{t_2})&space;=&space;-\log&space;\frac{\exp(s(\textbf{z}_i^{t_1},&space;\textbf{z}_i^{t_2})/\tau)}{&space;\sum\limits_{\substack{k=1&space;\\&space;k&space;\neq&space;i}}^{N}&space;\exp(s(\textbf{z}_i^{t_1},&space;\textbf{z}_k^{t_1})/\tau)&space;&plus;&space;\sum\limits_{\substack{k=1}}^{N}&space;\exp(s(\textbf{z}_i^{t_1},&space;\textbf{z}_k^{t_2})/\tau)}"/>

### CMID Loss

<img src = "https://latex.codecogs.com/svg.image?\mathcal{L}_{cmid}&space;=&space;\frac{1}{2N}&space;\sum_{i=1}^{N}[c(i,&space;\textbf{z},&space;\textbf{h})&space;&plus;&space;c(i,&space;\textbf{h},&space;\textbf{z})]"/>

where,

<img src="https://latex.codecogs.com/svg.image?c(i,&space;\textbf{z},&space;\textbf{h})&space;=&space;-\log&space;\frac{\exp(s(\textbf{z}_i,&space;\textbf{h}_i)/\tau)}{&space;\sum\limits_{\substack{k=1&space;\\&space;k&space;\neq&space;i}}^{N}&space;\exp(s(\textbf{z}_i,&space;\textbf{z}_k)/\tau)&space;&plus;&space;\sum\limits_{\substack{k=1}}^{N}&space;\exp(s(\textbf{z}_i,&space;\textbf{h}_k)/\tau)}" />
