### ISSUE TITLE
CrossPoint pretrained models with pointnet feature extractor

### ISSUE THREAD

**Issue by superheromeZzh** [MohamedAfham/CrossPoint#3]
Thank you for your excellent work.  Can you provide the pretrained models with pointnet feature extractor?

**Comment by MohamedAfham** [comment]
Thanks for the interest in our work. We'll be sharing the pre-trained models using PointNet feature extractor soon. However, feel free to train the model yourself using the PointNet codebase provided in https://github.com/WangYueFt/dgcnn/blob/master/pytorch/model.py

All the implementation details are provided in the paper.
