### ISSUE TITLE
Downstream tasks 3D Object classification 

### ISSUE THREAD

**Issue by curryanswer** [MohamedAfham/CrossPoint#4]
thanks for your great work! 
I'm confused that why you fit a simple linear SVM classifier on the train split of the classification datasets in 3D object classification? where can I find the corresponding code?

**Comment by MohamedAfham** [comment]
Hi, 
We are following the standard protocol of self-supervised learning setting. We fit a linear SVM on the feature vectors obtained after feeding the training split data to the pre-trained backbone.

You can find the downstream 3D object classification code at ```eval_ssl.ipynb``` notebook.

**Comment by hjw520365** [comment]
thanks for your great work!I have a question for this, when I train the model.
![QQ截图20220320082356](https://user-images.githubusercontent.com/49296581/159142919-de4a26c4-0f2a-40b0-bc16-fd2050b1f385.png)

**Comment by MohamedAfham** [comment]
@hjw520365 since the comment differs from the issue topic, feel free to create a new issue and I'm more than happy to comment on it. Thanks !
