### ISSUE TITLE
How did you get the 2D images corresponding to the ModelNet40, ScanObjectNN point cloud data? The content inside eval_ssl.ipynb looks incomprehensible, can you provide the original .py file code?

### ISSUE THREAD

**Issue by 2311762665** [MohamedAfham/CrossPoint#5]
Hello, dear author! How did you get the 2D images corresponding to the ModelNet40, ScanObjectNN point cloud data? The content inside eval_ssl.ipynb looks incomprehensible, can you provide the original .py file code?

**Comment by MohamedAfham** [comment]
As mentioned in the paper, we used the rendered 2D images only during the pre-training stage. All the downstream tasks are performed on the pre-trained point cloud feature extractor. 

During  pre-training, we used ShapeNet data and the corresponding 2D images are obtained from [1] as mentioned in the paper. Can you let me know which part of the notebook is incomprehensible ? We used the same notebook to produce the reported results in the paper.

[1] Qiangeng Xu, Weiyue Wang, Duygu Ceylan, Radomir Mech, and Ulrich Neumann. DISN: Deep implicit surface network for high-quality single-view 3D reconstruction. In Advances in Neural Information Processing Systems, volume 32, 2019

**Comment by 2311762665** [comment]
I tried to open the eval_ssl.ipynb file inside jupyter with no problem. Also, please tell me which version you used when you did the ScanObjectNN experiment, and the partition should be ‘trainning’, right?

**Comment by MohamedAfham** [comment]
Sorry for the delay in response.

We use the standard same version of ScanObjectNN as the previous works used. Kindly refer to [1] for more details. The partition should 'training' to fit the linear classifier and evaluated in the 'testing' partition.

[1] Hanchen Wang, Qi Liu, Xiangyu Yue, Joan Lasenby, and Matthew J. Kusner. Unsupervised point cloud pre-training via occlusion completion. In International Conference on Computer Vision, ICCV, 2021
