### ISSUE TITLE
Can't download the dataset using gdown 

### ISSUE THREAD

**Issue by Phoebe-ovo** [MohamedAfham/CrossPoint#9]
When using the download_data.sh, it will raise the error: 
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

How to use gdown to download the dataset?

**Comment by ruby1ring** [comment]
> When using the download_data.sh, it will raise the error: requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
> 
> How to use gdown to download the dataset?

hahaha. thx，i use http and dont use gdown, copy url to chrome can down datasets.

**Comment by MohamedAfham** [comment]
Hi @Phoebe-ovo ,

I rechecked it in another machine and it is working well. Make sure you have gdown installed.
